### PR TITLE
refactor(logs): zerolog introduced

### LINKED ISSUE #283: Introduce zerolog
Instead of the default `log` package, there is a growing need for more advanced logging capabilities.

The library zerolog seems nice, fast & clean.
Note the features:
- multi-level
- stacktrace

TODO:
- add new library zerolog
- replace all `log` imports with zerolog imports
- configure it as https://github.com/rs/zerolog#pretty-logging
- everything can be logged as Info, as changing these will be a separate issue

### PR DESCRIPTION
**Pull request by tg44**
fixes #283

 - Added zerolog as dep
 - Used zerolog includes instead of log
 - Where the build failed I changed;
   - `PrintLn` to 
     - `Error().Err(err).Stack().Msg()` if it logged an `err`
     - `Error().Msg()` if it contained the word `error:`
     - `Warning().Msg()` if it contained the word `warning:`
     - `Info().Str().Msg()` if it had params
     - `Print` otherwise
   - `Fatal` to `Fatal().Err(err).Stack().Msg()`
   - `Panic` to `Panic().Err(err).Stack().Msg()`

### CODE REVIEW

**Review by nandor-magyar — CHANGES_REQUESTED** [review]
All good :+1:  I am in shock :exploding_head:
I didn't expect this to be done this quickly.

As I wrote in the issue, I would prefer pretty printed output, since I haven't seen any configurations it might be default (json?).
That can stay (we will need it eventually), expect for our CLI component.

Its entrypoint is in `cmd/dyo/main.go`, the related messages are to be pretty printed, please add the necessary configuration.

Otherwise, looking good! :100:

**Comment by tg44** [comment]
I added the needed line.

**Review by nandor-magyar — APPROVED** [review]
LGTM :+1:

**Comment by c3ppc3pp** [comment]
The only complaint I have for now is an unsigned commit. Please sign it! Awesome work you did there! :+1:

**Comment by tg44** [comment]
done, and I had nothing to rebase to

**Review by robot9706 — APPROVED** [review]
LGTM 😎

**Review by polaroi8d — APPROVED** [review]

**Pull request merged**
