### PR TITLE
chore(crux-ui): changed try and catch

### PR DESCRIPTION
**Pull request by oriapp**
regarding issue #270

### CODE REVIEW

**Review by polaroi8d — APPROVED** [review]
Thanks, good job!

**Review by robot9706 — APPROVED** [review]
LGTM 😎

**Comment by robot9706** [comment]
Please [sign your commits](https://github.com/dyrector-io/dyrectorio/blob/develop/CONTRIBUTING.md#commit-signatures) then the PR can be merged 🚀

**Comment by oriapp** [comment]
Will do asap

**Comment by polaroi8d** [comment]
@oriapp you need any help with signing your commits?

**Comment by oriapp** [comment]
@polaroi8d No, I'll push the verify changes in a few minutes

**Comment by oriapp** [comment]
https://github.com/dyrector-io/dyrectorio/pull/281

**Pull request closed without merging**
