### PR TITLE
feat(web): rework deployment screen

### PR DESCRIPTION
**Pull request by robot9706**
Added status filter to list.
Reworked table design.
Removed status badge (list + deploy page)
Rearranged columns.
Fixed "exited" status color.
Fixed status badge size on deploy page.

### CODE REVIEW

**Review by polaroi8d — CHANGES_REQUESTED** [review]
I'm know that not related to this task, but can you add a deploy action in the table? Furthermore, if a node is not connected please show the error modal, and don't allow it to deploy.

**Review by balanceee — APPROVED** [review]
LGTM

**Comment by robot9706** [comment]
Moved back to draft, after talking with @polaroi8d. Adding some stuff to the new deployment card.

**Review by polaroi8d — APPROVED** [review]
LGTM

**Pull request merged**
