### PR TITLE
fix(crux-ui): fixes the sidebar height to scrollable

### PR DESCRIPTION
**Pull request by chandhuDev**
- It adds the sidebar to scrollable when the user screen height is small

### CODE REVIEW

**Review by polaroi8d — CHANGES_REQUESTED** [review]
image

Thanks @chandhuDev for your contribution, we are really appreciate your help 👍🏻 

Only a few minor issue with it. The scrollbar is functioning, but unfortunately, certain parts of the menu still overlap. Since there's already a scrollbar, it would be great if the margin could be maintained between all the sections.

**Comment by m8vago** [comment]
Thanks for the PR!

I beleive it would be better solution to just simply let the menu's background grow vertically, so it fills the available space:
image

@polaroi8d what do you think?

**Comment by chandhuDev** [comment]
Well, is this solution for only the sidebar settings section or complete sidebar?

**Comment by chandhuDev** [comment]
If it is the complete sidebar to grow vertically, then paddings, margins respective to each element would dynamically change based on screen size

**Comment by m8vago** [comment]
I think it should affect the complete sidebar.

**Comment by chandhuDev** [comment]
No problem I will try that and share the screenshot for review

**Comment by chandhuDev** [comment]
Screenshot (391)
Screenshot (395)
Screenshot (396)

**Comment by chandhuDev** [comment]
when the sidebar height grows vertically, each and every sections in the sidebar would take up same space. These above images are of different screen heights. Would like to know what you guys think about this ?

**Comment by chandhuDev** [comment]
we can also do one thing, based on screen size , we can update the padding and text-size changes dynamically based on some event making sure that every section should take up equal space and fits to height of the sidebar.

**Comment by polaroi8d** [comment]
It would be good if the first part, 'settings,' were fixed to the bottom of the screen, while the rest remains at the top as it is now, and if the screen is very large, then only a space between 'settings' and the top ('dashboard, project, component') grow. What do you think?

**Comment by polaroi8d** [comment]
> That means settings would become sticky to sidebar bottom and rest of components would appear on top even if the screen becomes larger ? @polaroi8d

Exactly!

**Comment by chandhuDev** [comment]
Screenshot (400)
Screenshot (401)
Screenshot (402)


would like you to see variations for different screen sizes? @polaroi8d

**Comment by polaroi8d** [comment]
> Screenshot (400) Screenshot (401) Screenshot (402)
> 
> would like you to see variations for different screen sizes? @polaroi8d

Yes it's cool.

**Comment by chandhuDev** [comment]
@polaroi8d pushed changes!

**Review by polaroi8d — CHANGES_REQUESTED** [review]
The base problem still exists. The growing its okay, but if the screen is smaller, the left bar is not growing as expected. 

image

**Comment by chandhuDev** [comment]
Well , it is because of the fixed font size , padding between elements not allowing settings section elements to be in the left side bar.

**Comment by chandhuDev** [comment]
I feel elements font size should decrease with the screen height decreases making sure to have every element on the screen.

**Comment by chandhuDev** [comment]
@polaroi8d hey I got you, I am working on it.

**Comment by polaroi8d** [comment]
Due to inactivity, I'm closing this issue. Thanks for the contribution if you have time and energy we can. easily reopen this.

**Pull request closed without merging**
