### PR TITLE
fix(web): deployment not moving to in-progress

### PR DESCRIPTION
**Pull request by robot9706**
After starting a deployment the state should move to "in progress".
Changed gRPC & Prisma deployment status mapping (to handle inProgress and IN_PROGRESS).

### CODE REVIEW

**Review by balanceee — APPROVED** [review]
LGTM

**Review by polaroi8d — APPROVED** [review]
LGTM

**Review by polaroi8d — APPROVED** [review]
Still LGTM.

**Review by m8vago — APPROVED** [review]
run `npm run format` pls if you didn't already

**Pull request merged**
