### PR TITLE
feat(web): integrates the mattermost webhook to notifications

### LINKED ISSUE #233: Implement Mattermost Webhook in Notifications
At present we have Discord, Slack & Team integration with webhooks. Please implement Mattermost Webhooks next to the existing ones. 

You have to work around the `web/crux/src/app/notification` for the backend and `web/crux-ui/src/components/notification` for the user interface. Furthermore, you have to extend the `protobuff` file with the new `NotificationType`.

Add regexp to check the validation of the webhook URL. 

Mattermost Webhook Documentation: https://developers.mattermost.com/integrate/webhooks/incoming/

### PR DESCRIPTION
**Pull request by chandhuDev**
fixes #233

### CODE REVIEW

**Comment by robot9706** [comment]
Please update your branch to dev, because it's very old. Also please read the [CONTRIBUTING.md](https://github.com/dyrector-io/dyrectorio/blob/develop/CONTRIBUTING.md#commit-signatures) especially the commit signature part because your commit is not signed.

Will check the PR after these.

Thank you.

**Comment by chandhuDev** [comment]
updating the branch to dev means resolving the conflicts , right? @robot9706

**Comment by robot9706** [comment]
@chandhuDev Yep, you can do it by merging develop to your branch and resolving all conflicts.

**Review by polaroi8d — CHANGES_REQUESTED** [review]
Missing commit signatures, you can find the docs here: https://github.com/dyrector-io/dyrectorio/blob/develop/CONTRIBUTING.md#commit-signatures

**Comment by polaroi8d** [comment]
`crux` lint is faling.

**Comment by m8vago** [comment]
Hi @chandhuDev 

Thank you for the contribution!

Please run `npm run format` in both the `web/crux` and the `web/crux-ui` folders.

**Review by robot9706 — APPROVED** [review]

**Review by polaroi8d — APPROVED** [review]

**Comment by chandhuDev** [comment]
fixes #233

**Pull request merged**
