### PR TITLE
fix(web): docker log config default value

### PR DESCRIPTION
**Pull request by AmorfEvo**
Fix: handle all supported Docker log configuration driver types properly from UI to actual deployment.
Fix: add node default case on the UI and set as default.
Unit tests for dagent logconfig driver type mapping.
Fix: makefile go linting doc comment.
Fix: typo in Traefik unsupported network mode warning message.

### CODE REVIEW

**Review by polaroi8d — APPROVED** [review]
Do not tested, but looks good to me (informal)

**Review by robot9706 — APPROVED** [review]
Tested, seems OK to me. ✨

**Comment by polaroi8d** [comment]
Do not merge.

**Comment by AmorfEvo** [comment]
As we discussed recently, the unspecified case has been refactored to be node default.

**Review by m8vago — APPROVED** [review]

**Pull request merged**
