### PR TITLE
test: add fuzz test for VersionCheck

### PR DESCRIPTION
**Pull request by adit-yaa**
- added fuzz test for version check
- updated duplicate test case in unit test for version check

### CODE REVIEW

**Comment by nandor-magyar** [comment]
Hey @adit-yaa! Thank your for efforts. Nice catch with the dupe.
There are no assertions in the fuzz function body. The fuzz function should be general, in the sense that it should allow (even expect) valid values.

**Comment by adit-yaa** [comment]
@nandor-magyar @polaroi8d I have added assertions and test input validation check to the test. Can you please check if this is what you suggested in your previous comment? I have added assertions using the existing functions present in `container.go`. Hopefully that wont be an issue. This is my first fuzz test, do let me know any suggestions/comments you have.

**Review by nandor-magyar — COMMENTED** [review]
First of all, thank you for all your efforts! I hope you could learn something. 
I will refactor your code and make this work (including your changes), so you could use the working sample to make another fuzzing tests if you are still interested. Expect me to soon open a PR mentioning this one, closing PR.

**Comment by adit-yaa** [comment]
Thanks for all the help @nandor-magyar. I will definitely be interested and look out for the PR.

**Comment by adit-yaa** [comment]
@nandor-magyar just noticed had put out a different commit by mistake to the branch have fixed the things in the newer commits. Sorry for all the trouble.

**Pull request closed without merging**
