### PR TITLE
feat(agent): add new docker container builder attribute: shell

### PR DESCRIPTION
**Pull request by raghav-rama**
Issue no. #220 
Will this be enough?
Is shell requiring other attributes(CMD, ENTRYPOINT) to be integrated?

### CODE REVIEW

**Comment by nandor-magyar** [comment]
It is good, the builder parameter is set, but the creation process does was not extended.
Check the Create func, pass the param.

Otherwise, all good. :+1:

**Comment by polaroi8d** [comment]
Good job ✋🏻 Could you please sign your commits? https://github.com/dyrector-io/dyrectorio/blob/develop/CONTRIBUTING.md#commit-signatures

**Comment by raghav-rama** [comment]
I would like to add that I only changed `golang\pkg\builder\container\container_builder.go` but all these other files were changed when I was resolving merge conflicts while rebasing...

**Review by nandor-magyar — COMMENTED** [review]
It is good now, but you have removed some files endings. Remove those from the change set.
Yes continuous work is going on develop, if there is a conflict, the one owning the PR has the responsibility to resolve the conflict and we prefer rebasing.

**Comment by raghav-rama** [comment]
> It is good now, but you have removed some files endings. Remove those from the change set

Done.

**Review by robot9706 — APPROVED** [review]
LGTM 😎

**Review by nandor-magyar — APPROVED** [review]

**Review by polaroi8d — APPROVED** [review]

**Comment by polaroi8d** [comment]
Please rebase the branch, after I'll merge 🙏🏻

**Comment by nandor-magyar** [comment]
If all commits are signed we can merge this, please sign all commits.

**Comment by raghav-rama** [comment]
How do I sign the first commit?

**Comment by polaroi8d** [comment]
> How do I sign the first commit? Is it possible?

Just squash your commits into 1 and sign it.

**Comment by raghav-rama** [comment]
> > How do I sign the first commit? Is it possible?
> 
> Just squash your commits into 1 and sign it.

Can I do it from GitHub?

**Comment by nandor-magyar** [comment]
You have to force push your changes that is sure, if you are uncertain about what is happening, make a backup before doing so.
Squashing and signing looks the simplest solution.
https://stackoverflow.com/questions/25356810/git-how-to-squash-all-commits-on-branch

**Pull request merged**
