### PR TITLE
fix(agent): swagger double init during testing

### PR DESCRIPTION
**Pull request by robot9706**

### CODE REVIEW

**Comment by robot9706** [comment]
Having problems with the swagger package. Closing for now.

**Review by nandor-magyar — APPROVED** [review]

**Comment by polaroi8d** [comment]
In general, we are using our service names in lower case, if there is no extra reason please use it like that.

**Comment by robot9706** [comment]
> In general, we are using our service names in lower case, if there is no extra reason please use it like that.

I'm guessing you are talking about the swagger command. I'm using an upper case name because `SwaggerInfo...` variable names are generated using the instance name, if I'd use a lower case name it'd look like `SwaggerInfocrane` not `SwaggerInfoCrane` which I think looks off.

**Comment by polaroi8d** [comment]
> > In general, we are using our service names in lower case, if there is no extra reason please use it like that.
> 
> I'm guessing you are talking about the swagger command. I'm using an upper case name because `SwaggerInfo...` variable names are generated using the instance name, if I'd use a lower case name it'd look like `SwaggerInfocrane` not `SwaggerInfoCrane` which I think looks off.

I am talking about instance names. (sorry for not mentioned)

**Review by polaroi8d — APPROVED** [review]
LGTM

**Pull request merged**
