### PR TITLE
feat: service category label for platform containers & hide containers based on category

### PR DESCRIPTION
**Pull request by robot9706**
- CLI adds `org.dyrectorio.service-category=_internal` labels to all platform containers.
- Added `labels` to agent container proto.
- Hide containers if their service category starts with an underscore or their kubernetes namespace is `kube-system`.

### CODE REVIEW

**Comment by polaroi8d** [comment]
Please add new labels to docker compose and CLI containers.

**Review by nandor-magyar — APPROVED** [review]
LGTM.

**Review by m8vago — APPROVED** [review]

**Review by polaroi8d — CHANGES_REQUESTED** [review]
`TypeError: Cannot read properties of undefined (reading 'org.dyrectorio.service-category')`

**Review by polaroi8d — APPROVED** [review]
Works locally.

**Pull request merged**
