### PR TITLE
doc: improve-readme-and-contributing-files

### PR DESCRIPTION
**Pull request by GuptaPratik02**
doc: improved-readme-and-contributing-file-issue-827
Issue - https://github.com/dyrector-io/dyrectorio/issues/827

Fixed 5 links in contributing file and 2 links in readme file.
Kindly review it once.
Thank you.

### CODE REVIEW

**Comment by GuptaPratik02** [comment]
Pardon @polaroi8d , I have renamed the earlier branch with the updated PR name and created new request but still it's not passing one check.
Can you please figure it out, what's the problem. I followed the contributing.md guide but still there's something not clearing.

**Comment by polaroi8d** [comment]
> Pardon @polaroi8d , I have renamed the earlier branch with the updated PR name and created new request but still it's not passing one check. Can you please figure it out, what's the problem. I followed the contributing.md guide but still there's something not clearing.

You should rename the PR title following the `CONTRIBUTING.md`, eg.: `doc:improve-readme-and-contributing-files`

**Comment by GuptaPratik02** [comment]
> > Pardon @polaroi8d , I have renamed the earlier branch with the updated PR name and created new request but still it's not passing one check. Can you please figure it out, what's the problem. I followed the contributing.md guide but still there's something not clearing.
> 
> You should rename the PR title following the `CONTRIBUTING.md`, eg.: `doc:improve-readme-and-contributing-files`

Changed.

**Comment by polaroi8d** [comment]
Sorry, you missed a whitespace between doc: and improve-    >>> `doc: improve`

**Comment by GuptaPratik02** [comment]
> Sorry, you missed a whitespace between doc: and improve- >>> `doc: improve`

Corrected, kindly check once

**Comment by GuptaPratik02** [comment]
Kindly merge it @polaroi8d , thanks for guiding :)

**Review by polaroi8d — APPROVED** [review]

**Comment by polaroi8d** [comment]
> Kindly merge it @polaroi8d , thanks for guiding :)

Waiting for at least one more approval.

**Review by nandor-magyar — APPROVED** [review]

**Review by gerimate — APPROVED** [review]
LGTM, good job!

**Review by robot9706 — APPROVED** [review]

**Pull request merged**
